### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by Nekiplay** [DSharpPlus/DotnetRPC#1]
How can I show new text?

My code looks something like this

> var client = new DotnetRPC.RpcClient("appid", true, Assembly.GetExecutingAssembly().Location);
try
{
client.Ready += async args =>
{
await client.SetActivityAsync(x =>
{
x.Details = "Онлайн: " + textBox1.Text;
x.State = "Online";
x.StartUnix = 0;
x.EndUnix = 0;
x.LargeImage = "12";
x.LargeImageText = "12";
x.SmallImage = "12";
x.SmallImageText = "12";
x.CurrentPartySize = 0;
x.MaxPartySize = 0;
x.PartyId = "";
});
};
await client.ConnectAsync();
await Task.Delay(15000);
client.Dispose();
await Task.Delay(15000);

**Comment by Naamloos** [comment]
You'll have to run SetActivityAsync again with the new data

**Comment by austanss** [comment]
duh. this is **simp**le
